### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by arvin243** [prontera/ideavimrc#1]
https://github.com/prontera/ideavimrc/blob/624909d53eb86e9130dc097ae0db079fe1010515/idea/idea.vimrc#L79

这下面好像是一个rerun命令, 不是return命令

**Comment by prontera** [comment]
> https://github.com/prontera/ideavimrc/blob/624909d53eb86e9130dc097ae0db079fe1010515/idea/idea.vimrc#L79
> 
> 这下面好像是一个rerun命令, 不是return命令

抱歉这是一个迟来的答复，这确实是rerun，个人而言常用于bugfix后的功能验证，因此靠leader f比较近
